# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 16, 14, 6, 6, 924695)),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('less_active', 'less_active'), ('independent', 'independent')], max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 16, 14, 6, 6, 918332)),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 16, 14, 6, 6, 918357)),
        ),
    ]
