# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-17 07:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 7, 14, 8, 556342)),
        ),
    ]
