# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-17 05:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0002_auto_20161116_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 5, 34, 15, 498107)),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 5, 34, 15, 491640)),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 5, 34, 15, 491667)),
        ),
    ]
