# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-24 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0002_auto_20161124_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
