# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-22 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant', to=settings.AUTH_USER_MODEL),
        ),
    ]
