# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-17 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0002_auto_20161117_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='experience',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 7, 20, 4, 692403)),
        ),
    ]
