# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-23 08:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0003_auto_20161122_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL),
        ),
    ]
