# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-17 07:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0003_auto_20161117_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 7, 43, 45, 756638)),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 7, 43, 45, 750305)),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 7, 43, 45, 750331)),
        ),
    ]
