# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-09 10:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0003_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
