# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0004_auto_20161117_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 7, 37, 30, 461549)),
        ),
    ]
