# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-23 14:35
from __future__ import unicode_literals

import consultant_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0004_auto_20161123_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_location',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, default=None, null=True, upload_to=consultant_app.models.get_attachment_file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='skype_username',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
