# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0005_auto_20161123_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
