# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 10:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultant_app', '0006_auto_20161117_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 10, 52, 32, 551713)),
        ),
    ]
