# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0007_auto_20161117_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='time',
        ),
        migrations.AddField(
            model_name='comment',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 12, 6, 17, 428066)),
        ),
        migrations.AddField(
            model_name='comment',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 12, 6, 17, 428152)),
        ),
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
