# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0008_auto_20161117_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 12, 6, 49, 692754)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 12, 6, 49, 692789)),
        ),
    ]
