# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-01 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0008_auto_20161130_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
