# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-29 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0008_auto_20161129_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='to_do_list',
            old_name='text',
            new_name='content',
        ),
    ]
