# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0009_user_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(b'pending', b'PENDING'), (b'completed', b'COMPLETED')], default=b'pending', max_length=10),
        ),
    ]
