# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-20 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0009_remove_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likess', to=settings.AUTH_USER_MODEL),
        ),
    ]
