# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-29 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0009_auto_20161129_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='clock',
        ),
        migrations.AddField(
            model_name='comment',
            name='read_unread',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='to_do_list',
            name='to_do_list_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
