# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-29 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0010_auto_20161129_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_unread',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='to_do_list',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
