# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-20 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0010_auto_20161220_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likess', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
