# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-22 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0013_auto_20161220_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultant_app.Technology'),
        ),
    ]
