# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0014_auto_20161222_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='send_by',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='log_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultant_app.Technology'),
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
