# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-08 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0014_auto_20161206_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='log_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
