# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-23 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0015_auto_20161222_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='technology',
            field=models.CharField(max_length=30),
        ),
    ]
