# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-09 06:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0015_user_log_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
