# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-23 11:04
from __future__ import unicode_literals

import consultant_app.models
import consultant_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0016_auto_20161223_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(default=None, null=True, upload_to=consultant_app.models.get_attachment_file_path, validators=[consultant_app.validators.validate_file_extension]),
        ),
    ]
