# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-09 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0016_notification_send_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
