# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0017_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultant_app.Technology'),
        ),
    ]
