# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-27 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0018_auto_20161215_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='supporter',
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='consultant_app.Project'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='project',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillset', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='technology',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='consultant_app.Technology'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='technology',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_do_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('supporter', 'SUPPORTER'), ('consultant', 'CONSULTANT')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
