# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-28 06:17
from __future__ import unicode_literals

import consultant_app.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0018_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=consultant_app.models.get_attachment_file_path),
        ),
    ]
