# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-27 07:13
from __future__ import unicode_literals

import consultant_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0019_auto_20161227_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=consultant_app.models.get_attachment_file_path),
        ),
    ]
