# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-28 07:21
from __future__ import unicode_literals

import consultant_app.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0019_auto_20161228_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=consultant_app.models.get_attachment_file_path, verbose_name='Image'),
        ),
    ]
