# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-27 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0020_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('less_active', 'LESS_ACTIVE'), ('independent', 'INDEPENDENT')], max_length=15, null=True),
        ),
    ]
