# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-28 06:23
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0021_auto_20161227_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='uploaded_images'),
        ),
    ]
