# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-28 06:24
from __future__ import unicode_literals

import consultant_app.models
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0022_auto_20161228_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=consultant_app.models.get_attachment_file_path),
        ),
    ]
