# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-28 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_app', '0022_auto_20161228_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_ppoi',
        ),
    ]
